// Code generated by mockery v2.14.0. DO NOT EDIT.

package farm

import (
	http "net/http"

	httprouter "github.com/julienschmidt/httprouter"
	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// HandlerAddFarm provides a mock function with given fields: w, r, params
func (_m *MockHandler) HandlerAddFarm(w http.ResponseWriter, r *http.Request, params httprouter.Params) {
	_m.Called(w, r, params)
}

// HandlerDeleteFarm provides a mock function with given fields: w, r, params
func (_m *MockHandler) HandlerDeleteFarm(w http.ResponseWriter, r *http.Request, params httprouter.Params) {
	_m.Called(w, r, params)
}

// HandlerGetFarm provides a mock function with given fields: w, r, params
func (_m *MockHandler) HandlerGetFarm(w http.ResponseWriter, r *http.Request, params httprouter.Params) {
	_m.Called(w, r, params)
}

// HandlerGetFarmByID provides a mock function with given fields: w, r, params
func (_m *MockHandler) HandlerGetFarmByID(w http.ResponseWriter, r *http.Request, params httprouter.Params) {
	_m.Called(w, r, params)
}

type mockConstructorTestingTNewMockHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHandler(t mockConstructorTestingTNewMockHandler) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
