// Code generated by mockery v2.14.0. DO NOT EDIT.

package pond

import (
	model "aquafarm/common/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

// DeletePondByID provides a mock function with given fields: ctx, req
func (_m *MockUsecase) DeletePondByID(ctx context.Context, req model.DeletePondByID) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DeletePondByID) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPond provides a mock function with given fields: ctx, req
func (_m *MockUsecase) GetPond(ctx context.Context, req model.GetPondReq) ([]model.Pond, error) {
	ret := _m.Called(ctx, req)

	var r0 []model.Pond
	if rf, ok := ret.Get(0).(func(context.Context, model.GetPondReq) []model.Pond); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Pond)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GetPondReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPondByID provides a mock function with given fields: ctx, req
func (_m *MockUsecase) GetPondByID(ctx context.Context, req model.GetPondByID) (model.Pond, error) {
	ret := _m.Called(ctx, req)

	var r0 model.Pond
	if rf, ok := ret.Get(0).(func(context.Context, model.GetPondByID) model.Pond); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.Pond)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GetPondByID) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertPond provides a mock function with given fields: ctx, req
func (_m *MockUsecase) InsertPond(ctx context.Context, req model.InsertPondReq) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.InsertPondReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertPond provides a mock function with given fields: ctx, req
func (_m *MockUsecase) UpsertPond(ctx context.Context, req model.UpsertPond) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UpsertPond) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUsecase(t mockConstructorTestingTNewMockUsecase) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
